spring.datasource.url: jdbc:mysql://localhost:3306/booklib?useSSL=false&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.ddl-auto: create
someParameter:
  value: 5463